name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: CYPRESS_INSTALL_BINARY=0 npm ci --legacy-peer-deps

      - name: Check types
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test:ci
      - name: Build frontend
        run: npm run build

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start grafana docker
        run: npm run server -- -d

      # E2E tests temporarily disabled due to grafana-e2e command path issues
      # - name: Run e2e tests
      #   run: yarn e2e

      - name: Stop grafana docker
        run: docker-compose down

      - name: Check for backend
        id: check-for-backend
        run: |
          if [ -f "Magefile.go" ]
          then
            echo "has-backend=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Go environment
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # Google Cloud SDK and backend tests temporarily disabled
      # - name: 'Set up Cloud SDK'
      #   if: steps.check-for-backend.outputs.has-backend == 'true'
      #   uses: 'google-github-actions/setup-gcloud@v1'
      # - name: Install Google Cloud SDK components
      #   if: steps.check-for-backend.outputs.has-backend == 'true'
      #   run: yes | gcloud components install beta cloud-firestore-emulator
      # - name: Test backend
      #   if: steps.check-for-backend.outputs.has-backend == 'true'
      #   uses: magefile/mage-action@v1
      #   with:
      #     version: latest
      #     args: coverage

      # Backend build temporarily disabled - requires mage/Go setup
      # - name: Build backend
      #   if: steps.check-for-backend.outputs.has-backend == 'true'
      #   uses: magefile/mage-action@v1
      #   with:
      #     version: latest
      #     args: buildAll
